version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
#  mysql:
#    image: mysql:8.0.21       # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
#    container_name: gshark-mysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    restart: "always"
#    ports:
#      - "13306:3306"  # host物理直接映射端口为13306
#    environment:
#      MYSQL_DATABASE:
#      MYSQL_ROOT_PASSWORD: 'madneal'
#      MYSQL_USER: 'gshark'
#      MYSQL_PASSWORD: 'gshark'
#    volumes:
#      - ./mysql:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 2s
#      retries: 10
#    networks:
#      network:
#        ipv4_address: 177.7.0.13

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: gshark-web
    restart: "always"
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./server
      dockerfile: deploy/serve/Dockerfile
    environment:
      - GSHARK_CONFIG=config.docker.yaml
    container_name: gshark-server
    volumes:
      - ./server/config.docker.yaml:/go/src/github.com/madneal/gshark/server/config.docker.yaml
    restart: "always"
    ports:
      - '9999:9999'
    networks:
      network:
        ipv4_address: 177.7.0.12

  scan:
    build:
      context: ./server
      dockerfile: deploy/scan/Dockerfile
    environment:
      - GSHARK_CONFIG=config.docker.yaml
    container_name: gshark-scanner
    volumes:
      - ./server/config.docker.yaml:/go/src/github.com/madneal/gshark/server/config.docker.yaml
    restart: "no"
    networks:
      network:
        ipv4_address: 177.7.0.14
